-- CREATE DATABASE

USE [master]
GO
IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'MonitorDB')
BEGIN
	CREATE DATABASE [MonitorDB]
	ALTER DATABASE [MonitorDB] SET RECOVERY SIMPLE 
	ALTER DATABASE [MonitorDB] MODIFY FILE ( NAME = N'MonitorDB', SIZE = 10MB , FILEGROWTH = 10MB )
	ALTER DATABASE [MonitorDB] MODIFY FILE ( NAME = N'MonitorDB_log', SIZE = 10MB , FILEGROWTH = 10MB )
END
GO

USE [MonitorDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 1;
